name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *" # Execução diária
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pacman Graph
        uses: khalidshrif/pacman-contribution-graph@master
        with:
          github_user_name: wellingtonspdev
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: pacman-graph
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
