name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *" # Execução diária à meia-noite para otimização de FinOps
  workflow_dispatch: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pacman Graph
        uses: abozanona/pacman-contribution-graph@2.4.0
        with:
          github_user_name: wellingtonspdev
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
